networks:
  app_network:
    driver: bridge

services:
  app:
    build:
      dockerfile: Dockerfile
    ports:
     - 8000:8000
    networks:
     - app_network
    depends_on:
     - redis
     - mongodb
    volumes:
     - mongodb_data:/data/db
     - app_data:/app

  frontend:
    build:
      dockerfile: web.Dockerfile
    ports:
      - 3000:80
    networks:
      - app_network
    depends_on:
      - app

  mongodb:
    image: mongo
    networks:
      - app_network
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    networks:
      - app_network
    env_file:
      - .envlocal
    depends_on:
      - mongodb

  redis:
    image: redis
    networks:
      - app_network
    volumes:
     - redis_data:/data

volumes:
  mongodb_data:
  app_data:
  redis_data: